### ISSUE TITLE
isDragReject not working

### ISSUE THREAD

**Issue by emkis** [Yaxian/vue3-dropzone#1]
### I used the `useDropzone` hook with this options:

```js
{
  maxSize: 5242880, // 5MB
  minSize: 209715, // 204,8 KB
  onDrop: (acceptedFiles: any, rejectedFiles: any) => {
    console.log({ acceptedFiles, rejectedFiles })
  },
}
```

And when I run `console.log` with` acceptedFiles` and `rejectedFiles` in the` onDrop` function, I get the right information.
However, the `isDragReject` property does not work respecting the values of` maxSize` and `minSize`.

When i set in the hook options the property `multiple: false`, then the `isDragReject` worked correctly when i tried to send more than one file.

Sorry my bad english, but im trying to help :star2:

**Comment by emkis** [comment]
### Example of the problem

You can see here, that when a drag one invalid file, that is logged on the list of `rejectedFiles`, the property `isDragReject` was `false`, but should be `true`.

And when i tried i set the `multiple: false` and try to drag multiple files, the `isDragReject` was correct.

![sample](https://user-images.githubusercontent.com/35054425/109397839-a1299e00-7917-11eb-9d3f-01ef529c7e2b.gif)

I hoje this GIF help you to understand the problem.

**Comment by Yaxian** [comment]
Thanks, I will check soon.

**Comment by Yaxian** [comment]
@emkis Hi, could you provide the code snippet to reproduce it?

**Comment by emkis** [comment]
@Yaxian sure.

**Template**
```vue
<div  v-bind="getRootProps()">
  <input v-bind="getInputProps()" />

  <p>isDragActive: {{ isDragActive }}</p>
  <p>isDragReject: {{ isDragReject }}</p>
</div>
```

**Script**
```vue
<script lang="ts">
import { defineComponent } from 'vue'
import { useDropzone } from 'vue3-dropzone'

export default defineComponent({
  setup(props) {
    const {
      getRootProps,
      getInputProps,
      isDragActive,
      isDragReject,
    } = useDropzone({
      maxSize: 5242880, // 5MB,
      minSize: 209715, // 204,8 KB
      onDrop: (acceptedFiles: any, rejectedFiles: any) => {
        console.log({ acceptedFiles, rejectedFiles })
      },
      multiple: false,
    })

    return {
      getRootProps,
      getInputProps,
      isDragActive,
      isDragReject,
    }
  },
})
</script>
```

**Comment by Yaxian** [comment]
Hi, I release [v0.0.6](https://github.com/Yaxian/vue3-dropzone/releases/tag/v0.0.6).

Could you check this version?

Thanks 😄

**Comment by emkis** [comment]
@Yaxian, of course, I'm going to try today and already let you know the result

**Comment by emkis** [comment]
@Yaxian the error unfortunately keeps happening :exploding_head:, how did you test it?

**Comment by Yaxian** [comment]
I found same issue here,  https://stackoverflow.com/questions/41450438/datatransferitems-getasfile-method-returning-null-for-files


> The dragenter event doesn't have access to the actual files. It can detect what files are being dragged but it can't access their content. This is why even though the DataTransfer.items object is populated, the DataTransfer.files object isn't, and the getAsItem method cannot be used on DataTransfer.items items.


About `DataTransfer`, see https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/getAsFileSystemHandle


When dragging, the file may be instanceof `DataTransferItem`  in `drag event`,  we can get the `{kind: "file", type: "image/jpeg"}`, but can not get the file `size`. so `minSize` and `maxSize` won't work.

`accept` works well when dragging.

After `drop`, we can get the file content, and `minSize` and `maxSize` will work.

**Comment by emkis** [comment]
Wow, it makes sense. At least we learned something new. Thanks for sharing and your time :zap:
