### ISSUE TITLE
onDrop parameter doesn't infer all properties

### ISSUE THREAD

**Issue by HabardiT** [Yaxian/vue3-dropzone#15]
I'm trying to use typescript with this awesome package, thank you for it.

  const onDrop: FileUploadOptions["onDrop"] = (acceptedFiles) => {
      acceptedFiles[0].
      emit("update:modelValue", acceptedFiles);
  };

the issue I'm facing is when typing acceptedFiles[0]. , it only shows 2 properties [type,size]. 
there are more properties defined in InputFile interface. 

please check the below screenshot

![alt text](https://i.imgur.com/grnVLmd.png)

I'm curious to why some properties are showing and others aren't.

**Comment by Yaxian** [comment]
Hi,
Try use `vue3-dropzone@2.0.1`, and

```typescript
const onDrop = (acceptedFiles: File[]) => {

}
```

**Comment by HabardiT** [comment]
> Hi, Try use `vue3-dropzone@2.0.1`, and
> 
> ```ts
> const onDrop = (acceptedFiles: File[]) => {
>   const file= acceptedFiles[0]
> }
> ```
> 
> Thanks

Hey, thanks a lot for this. it's working!
