### ISSUE TITLE
Add emit within dropzone

### ISSUE THREAD

**Issue by mrkprdo** [Yaxian/vue3-dropzone#17]
Tried adding a button **within** dropzone  and emit callback fn.
Callback/emit seems to work but it opens the file explorer when button is clicked.

Is there a way to unbind click listener from that child button?

**Comment by Yaxian** [comment]
Hi,

Could you show me some code snippet  that I can know the issue and  fix it?

Thank you.

**Comment by mrkprdo** [comment]
Hi, This is the sample rough snippet, just typed this on top of my head.
```javascript
<template>
  <div v-bind="getRootProps()">
    <input v-bind="getInputProps()" type="file" name="file" />
    <p>Upload here</p>
    <Thumbnail class="upload-icon"/>
    <button @click="$emit('remove')"> x </button>  <== emit is triggered, but the open-file explorer pops-up 
  </div>
</template>
<script>
import { useDropzone } from 'vue3-dropzone'
export default {
  emits: ['remove'],
  setup() {
	function processFiles() { ... }
    function onDrop(acceptFiles, rejectedFiles) {
      processFiles(acceptFiles, rejectedFiles)
    }
    const { getRootProps, getInputProps, ...rest } = useDropzone({
      onDrop,
      accept: ...,
      noClick: ...,
      multiple: ...,
    })

    return {
      getRootProps,
      getInputProps,
      ...rest,
    }
  },
}
</script>
```

To imagine the use-case, once the file is dropped on the dropzone, it will have a thumbnail, and within that thumbnail, i have a "remove" button, which supposedly removes the file that was dropped.

**Comment by Yaxian** [comment]
Hi,
it may work by using `@click.stop`, like `<button @click.stop="$emit('remove')"> x </button>` .

Thanks.

**Comment by mrkprdo** [comment]
It worked. Thanks!
