### ISSUE TITLE
nuxt

### ISSUE THREAD

**Issue by fyllepo** [Yaxian/vue3-dropzone#2]
Hi there,

Is there any support for nuxt currently? has anyone managed to get this package running in their nuxt projects?

I am getting "e.ref is not a function", thanks!

The only difference I have from the example code is using nuxts  `defineComponent` function, as opposed to vues own.

**Comment by Yaxian** [comment]
Hi @fyllepo , thanks.

I find that  nuxtjs not release to support vue3 now. see https://github.com/nuxt/nuxt.js/issues/5708

This package is only support for vue3. 

Could you provide the `nuxtjs version` and `vue version` you used?

Thanks 😃

**Comment by fyllepo** [comment]
@Yaxian  So sorry, you are right.

I have been using the nuxt @nuxtjs/composition-api package, which allows the use of the vue composition API., hence I had thought/forgotten it was not actually vue 3.

In this case, I'll use a different implementation of dropzone.
