### ISSUE TITLE
Type error in 2.1.0

### ISSUE THREAD

**Issue by Cameron1818** [Yaxian/vue3-dropzone#21]
Update caused type error in the following function when using the example code from the readme. This works fine for me in 2.0.1. 

```
function fileAccepted(file, accept) {
    var isAcceptable = file.type === 'application/x-moz-file' || accepts(file, accept);
    return [isAcceptable, isAcceptable ? null : getInvalidTypeRejectionErr(accept)];
}
```

accepts(file, accept) expects a function, should we be setting up the code with a callback?

**Comment by dbcoder14** [comment]
I encountered the same issue, and after spending hours on it, I decided to compare the package-lock files from earlier commits.

And found one difference.
vue3-dropzone: ^2.0.1

Replaced version

    "node_modules/vue3-dropzone": {
          "version": "2.1.0",
          "resolved": "https://registry.npmjs.org/vue3-dropzone/-/vue3-dropzone-2.1.0.tgz",
          "integrity": "sha512-UwVUgN5ckew72GlKqRKYHo4PkFyihONjxIIAkGFHj24pjrJmrRAz+9YnDTYaBmKuq9KH0YB5y31MtaETLahLOA==",
          "dependencies": {
            "attr-accept": "^2.2.2",
            "file-selector": "^0.2.4"
          },
          "peerDependencies": {
            "vue": ">=3"
          }
        },

With following:

      "node_modules/vue3-dropzone": {
        "version": "2.0.1",
        "resolved": "https://registry.npmjs.org/vue3-dropzone/-/vue3-dropzone-2.0.1.tgz",
        "integrity": "sha512-jY36ZhIpGCxyok6cKxFb2s9s15c1KXmLHxcHzHhjoPzZ5IHW7+2RrnYUenCdq88ym66KyknscNkJYJzh3C23hw==",
        "dependencies": {
          "attr-accept": "^2.2.2",
          "file-selector": "^0.2.4"
        },
        "peerDependencies": {
          "vue": ">=3"
        }
      },

This is a temporary solution, I will be waiting for the fix, thanks

**Comment by Yaxian** [comment]
@Cameron1818 Could you show me more details like sceenshot on ts error?
`accepts(file, accept)` is a function, which is imported from 'attr-accept' lib

**Comment by dbcoder14** [comment]
@Yaxian I attached the error screenshot as well as my package.json & package-lock.json.
When I do an npm update & get dropzone 2.1.0, things start breaking, let me know if you need anything else?


  ```
Uncaught runtime errors:
  ERROR
  attr_accept__WEBPACK_IMPORTED_MODULE_3__ is not a function. (In 'attr_accept__WEBPACK_IMPORTED_MODULE_3__(file, accept)', 'attr_accept__WEBPACK_IMPORTED_MODULE_3__' is an instance of Object)
  fileAccepted@
  @
  forEach@[native code]
  @
  ![Skærmbillede 2023-08-22 kl  08 45 34](https://github.com/Yaxian/vue3-dropzone/assets/96175955/7510cc4b-28b6-45f4-917d-524a34506de5)
  <img width="1434" alt="Skærmbillede 2023-08-22 kl  08 46 11" src="https://github.com/Yaxian/vue3-dropzone/assets/96175955/a74dc1d5-b889-48e5-998e-665e8d1e2c86">
```

**Comment by Yaxian** [comment]
@dbcoder14 
Is there `attr-accept` lib in your `node_modules`? 
Try `rm -rf node_modules && yarn install` to download `attr-accept`

**Comment by Yaxian** [comment]
#25

**Comment by Yaxian** [comment]
@Cameron1818  @dbcoder14 
Thanks, please try `vue3-dropzone@2.1.1` to fix this problem
