### ISSUE TITLE
Drop image from same page

### ISSUE THREAD

**Issue by cxammar** [Yaxian/vue3-dropzone#24]
Hello, I want to make my drag and drop component only accept images from the page itself the drop component is located on. I use this functionality to change the profile image from a gallery of pre selected photos I allow.

I'm facing two issues:
1. When dragging and dropping from the page itself to the dropzone the useDropzone onDrop doesn't notice the drop, as opposed to when I drop from my local computer to the dropzone where.
2. How can I filter to make sure only images from the page itself are being uploaded and not abritrary images either from another page or from the local pc?

Thanks

**Comment by Yaxian** [comment]
Hello, could you show more details, like provide some code snippets or demo?

**Comment by cxammar** [comment]
Sure. Here I display the profile image which is actually a hidden dropzone:

```
                <div v-bind="getRootProps()" class="flex flex-grow h-[75%]">
                    <img class="rounded-md transition-all object-cover w-full h-full"
                        :class="isDragActive ? 'opacity-5' : 'opacity-100'" :src="FetchedPatient.profile_image_url"
                        alt=" " />
                    <input v-bind="getInputProps()" />
                </div>
```

I'm trying to be able to drop images from the same page the profile image (above code) is in, to the dropzone. Not from my local pc, but directly from the same webpage as the dropzone is in.

The issue i'm facing is that the dropzone doesn't recognize the files when dropping from the site itself but does work when dropping from my local pc.

If i use @drop.prevent on the div, it picks up the image so I'm guessing it has to do with the default browser behaviour overlapping with the vue 3 dropzone behaviour

**Comment by cxammar** [comment]
Hi, sorry to bother again, any idea on how to achieve this ?

**Comment by Yaxian** [comment]
@cxammar 
Did you check the devtools of online web? Is there error?
Could you show me the online web url, so I can try to debug it? 
or could you show me a video record about the activity where `dropzone` not work?

**Comment by cxammar** [comment]
Hello @Yaxian the issue i'm talking about it's not a bug itself but a weird implementation that i think falls out of the scope of the dropzone. I'll find another way to achieve the result, thanks and sorry for the inconvenience.
