### ISSUE TITLE
Using the readme code is giving error

### ISSUE THREAD

**Issue by zohaibkhan-wiot** [Yaxian/vue3-dropzone#25]
I have used the code from the README but it gave me the following error: 

```
index.esm.js:135 Uncaught (in promise) TypeError: (0 , import_attr_accept.default) is not a function
    at fileAccepted (index.esm.js:135:66)
    at index.esm.js:389:30
    at Array.forEach (<anonymous>)
    at index.esm.js:388:23
```

**Comment by Yaxian** [comment]
npm or yarn, which tool do you use?
what is the tool's version?

**Comment by Yaxian** [comment]
1. does `node_modules` dir include `attr-accept` lib?
2. which build tool you use, webpack , rollup, or vite?
3. Could you show me a demo?

**Comment by klintuesin** [comment]
[https://github.com/react-dropzone/attr-accept/issues/29#issuecomment-1282512349](url)
i change from
`import accepts from "attr-accept";`

to
`import A from "attr-accept";`
`const accepts = A.default ? A.default : A;`

work for me

**Comment by Yaxian** [comment]
> [react-dropzone/attr-accept#29 (comment)](https://github.com/react-dropzone/attr-accept/issues/29#issuecomment-1282512349) i change from `import accepts from "attr-accept";`
> 
> to `import A from "attr-accept";` `const accepts = A.default ? A.default : A;`
> 
> work for me

@klintuesin Thanks.

@zohaibkhan-wiot please try `vue3-dropzone@2.1.1`
