### ISSUE TITLE
isDragActive and isDragReject don't work correctly in example

### ISSUE THREAD

**Issue by boggsey** [Yaxian/vue3-dropzone#3]
I just started diving into Vue 3 and dropzone for the first time, so forgive me if I'm missing something. I am able to pull this project down and run the example successfully. The examples are using the local project and not the bundled package.

However, when I create a basic Vue 3 instance with vue3-dropzone v0.0.5 or v0.0.6, isDragActive and isDragReject do not work inside of the v-if statements.

Steps to reproduce:
- Clone https://github.com/boggsey/vue3-dropzone-test
- yarn install & yarn serve
- Attempt to drag a .jpg file on to the input
- Observe that the v-if for isDragActive does not fire

Minimal repro can be found here: [https://github.com/boggsey/vue3-dropzone-test](https://github.com/boggsey/vue3-dropzone-test)

**Comment by Yaxian** [comment]
It seems that I did not publish the build files to npm registry correctly.

I have fixed it. Please update to version `0.0.7`.

Thanks 😄

**Comment by boggsey** [comment]
Thank you! It does seem to be working correctly, however, isDragReject is always true even if the file type is correct. I have updated the existing repo to 0.0.7. This might be a separate issue as it seems to be behaving that way in the example, as well.
