### ISSUE TITLE
isDragReject is always true in the example

### ISSUE THREAD

**Issue by boggsey** [Yaxian/vue3-dropzone#4]
When I create a basic Vue 3 instance with vue3-dropzone v.0.0.7, isDragReject always displays true in the v-if, even if the file type is correct (jpg). Even though isDragReject always displays true, the file will correctly log a .jpg in acceptedFiles in the onDrop function.

Steps to reproduce:

- Clone https://github.com/boggsey/vue3-dropzone-test
- yarn install & yarn serve
- Attempt to drag a .jpg file on to the input
- Observe that the v-if for isDragReject is true

Minimal repro can be found here: [https://github.com/boggsey/vue3-dropzone-test](https://github.com/boggsey/vue3-dropzone-test)

**Comment by Yaxian** [comment]
<img width="236" alt="image" src="https://user-images.githubusercontent.com/9707805/159620614-93cef01e-2894-4fe2-9676-7232384e5433.png">

Is the MIME real `jpg`,  not  `jpeg`?
