### ISSUE TITLE
Split getRootProps into Drop and Select (event onclick)

### ISSUE THREAD

**Issue by yassinrais** [Yaxian/vue3-dropzone#6]
Again ! 

Guys can you split the getRootProps into two parts

one just for drag drop files 

and the other one for selecting a file 

because mixing those two make it limited to use 

Sometime clicking the drop zone does not mean choosing a file,
Imagine you have a drop zone and inside you have the list of drag-dropped files and each file has a delete button , if you try to click in the button it will open the file dialog 

I don't know if you got the idea 😅

Thanks.
Greetings.

**Comment by Yaxian** [comment]
Sorry for late.
In that case, we should stop propagation on `<DeleteButton />`
