### ISSUE TITLE
How to use multiple dropzone on single compoment - discussion

### ISSUE THREAD

**Issue by sagardspeed2** [Yaxian/vue3-dropzone#7]
Hi Mates, @Yaxian ,
Need some help with this plugin.

How to setup multiple dropzone in single component ?

There is no any further documentation related this plugin

Thanks in advance.

**Comment by Yaxian** [comment]
pass `multiple : true` in `useDropzone` options

```
setup() {
  function onDrop() {}
  const { getRootProps, getInputProps, ...rest } = const useDropzone({ onDrop, multiple: true })
}
```

Thanks

**Comment by Yaxian** [comment]
Can it work, can I close this issue?
