### ISSUE TITLE
Get the actual File from the input.

### ISSUE THREAD

**Issue by UXandre** [Yaxian/vue3-dropzone#8]
Hi all,

I hope you are well. I've been trying to get the actual file so I can send it to the backend and store the image, but failed to do it.

Though the `acceptFiles` in `function onDrop(acceptFiles, rejectReasons)` seems only return an array of File objects, they turned out to be a normal object that I can't retrieve the file in the backend. The only things I receive in the backend are the path, name, and a few other props in the object.

I was wanting to do something equivalent to the following:

```
var formData = new FormData();
var imagefile = document.querySelector('#file');
formData.append("image", imagefile.files[0]);
axios.post('upload_file', formData, {
    headers: {
      'Content-Type': 'multipart/form-data'
    }
})
```

Side note: I'm using Laravel 8 in the backend and `$request->hasFile('image')` returns false axios.post the acceptFiles.

**Comment by Yaxian** [comment]
Hi, you can try to use `formData` in `onDrop(acceptFiles)` callback, like:

```

function onDrop(acceptFiles) {
  const formData = new FormData();
  const file = acceptFiles[0]
  formData.append("image", imagefile.files[0]);
  axios.post('upload_file', formData, {
      headers: {
        'Content-Type': 'multipart/form-data'
      }
  })
}


```

**Comment by UXandre** [comment]
@Yaxian Thanks so much for this. Works like a charm. I've done some tweaks to save multiple files at one request but your suggestion got me in the right direction! Will try to submit a PR to update the doc a little bit. Just so some people's hours can be saved!
